# Generated by Django 5.1.6 on 2025-02-24 20:00

import django.db.models.deletion
import mptt.fields
import tools.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("title", models.TextField(default="", verbose_name="题目")),
                ("symptom", models.IntegerField(default=0, verbose_name="症状")),
                (
                    "symptom_type",
                    models.IntegerField(default=0, verbose_name="症状类型"),
                ),
                ("mode", models.IntegerField(default=0, verbose_name="题目类型")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="question.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "试题",
            },
        ),
    ]
