# Generated by Django 5.1.6 on 2025-02-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.IntegerField(default=0, verbose_name="题目顺序，每一级都有"),
        ),
    ]
