# Generated by Django 5.1.6 on 2025-02-26 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0002_question_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("parent", "order")},
        ),
    ]
