# Generated by Django 5.1.6 on 2025-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0003_alter_question_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="question",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["level", "order"], name="level_order"),
        ),
    ]
