# Generated by Django 5.1.6 on 2025-02-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0004_alter_question_unique_together_question_level_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="title_number",
            field=models.CharField(default="", max_length=128, verbose_name="题号"),
        ),
    ]
