# Generated by Django 5.1.6 on 2025-03-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0005_question_title_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="title_level",
            field=models.IntegerField(default=0, verbose_name="题号等级"),
        ),
    ]
