# Generated by Django 5.1.6 on 2025-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0006_question_title_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="clear_ids",
            field=models.JSONField(
                default=list, verbose_name="选择了这一题，需要清除哪些选项"
            ),
        ),
    ]
