# Generated by Django 5.1.6 on 2025-03-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0007_question_clear_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_qualitative",
            field=models.BooleanField(default=False, verbose_name="是否定性"),
        ),
    ]
