# Generated by Django 5.1.6 on 2025-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0008_question_is_qualitative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="is_qualitative",
        ),
        migrations.RemoveField(
            model_name="question",
            name="symptom",
        ),
        migrations.RemoveField(
            model_name="question",
            name="symptom_type",
        ),
        migrations.AddField(
            model_name="question",
            name="jl",
            field=models.JSONField(default=dict, verbose_name="焦虑"),
        ),
        migrations.AddField(
            model_name="question",
            name="yu",
            field=models.JSONField(default=dict, verbose_name="抑郁"),
        ),
    ]
