"""
Django settings for pcm project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from importlib.util import find_spec
from pathlib import Path
import redis

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "development-only-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_celery_results",
    "django_celery_beat",

    "rest_framework",
    "mptt",
    "question",
    "patient",
    "user",
    "llm",
    "system",
    "speech"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pcm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pcm.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": os.getenv("PCM_DB_HOST", "localhost"),
        "NAME": os.getenv("PCM_DB_NAME", "pcm"),
        "PASSWORD": os.getenv("PCM_DB_PASSWORD", ""),
        "PORT": os.getenv("PCM_DB_PORT", "3306"),
        "USER": os.getenv("PCM_DB_USER", "root"),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    "CHECKUSERID",
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'taskId',
    'sourceCode',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    "X-BULK-OPERATION",
    'Pragma',
    'domain-name',
)

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        # 设置使用JSON渲染器
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 使用TokenAuthentication认证
        # 'rest_framework.authentication.TokenAuthentication',
        "tools.auth.TokenAuthentication"
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 使用IsAuthenticated权限类确保已登录用户才能访问API
        # 'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'tools.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'tools.page.CustomPaginationSerializer',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend', "rest_framework.filters.OrderingFilter"
    ],
}

# ========================== 微信
code2session_url = "https://api.weixin.qq.com/sns/jscode2session"
get_access_token = "https://api.weixin.qq.com/cgi-bin/token"
app_id = os.getenv("WECHAT_APP_ID", "")
app_secret = os.getenv("WECHAT_APP_SECRET", "")
wx_env = ""

pdf_dir = ""

# ========================== 方剂 RAG
RAG_CORPUS_PATH = Path(
    os.getenv(
        "PCM_RAG_CORPUS_PATH",
        BASE_DIR.parent / "dacidian_text" / "corpus" / "fangji_entries.jsonl",
    )
)
RAG_SYNDROME_INDEX_PATH = Path(
    os.getenv(
        "PCM_RAG_SYNDROME_INDEX_PATH",
        BASE_DIR.parent / "dacidian_text" / "volume_11" / "volume_11_syndrome_index.jsonl",
    )
)
RAG_INDEX_PATH = Path(
    os.getenv("PCM_RAG_INDEX_PATH", BASE_DIR / "var" / "rag" / "fangji.sqlite3")
)

# ========================== 在线大模型
DEFAULT_LLM_MODEL = os.getenv("PCM_DEFAULT_LLM_MODEL", "deepseek-v4-pro")

# ========================== redis
REDIS_HOST = os.getenv("PCM_REDIS_HOST", "127.0.0.1")
REDIS_PORT = os.getenv("PCM_REDIS_PORT", "6379")

# ========================== 项目ip地址/域名，二维码要用这个信息
HOST = os.getenv("PCM_PUBLIC_URL", "http://127.0.0.1")

currant_env = os.getenv("PCM_ENV", os.getenv("CURRANT_ENV", "local"))
print("currant_env...", currant_env)
if currant_env == "local":
    if find_spec("pcm.settings_local"):
        from .settings_local import *
    else:
        from .settings_sqlite import *
elif currant_env == "test":
    from .settings_sqlite import *
    from .settings_test import *
elif currant_env == "prod":
    from .settings_prod import *
elif currant_env == "pilot":
    from .settings_pilot import *

# ========================= celery
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = False
DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_RESULT_BACKEND = 'django-db'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/2'

redis_cli = redis.Redis(
    connection_pool=redis.ConnectionPool(
        host=REDIS_HOST, port=REDIS_PORT, encoding="utf-8", max_connections=20, db=0
    )
)

# ======================== appkey
ALI_AK = os.getenv("ALIYUN_ACCESS_KEY_ID", "")
ALI_AK_SECRET = os.getenv("ALIYUN_ACCESS_KEY_SECRET", "")
ALIYUN_NLS_APPKEY = os.getenv("ALIYUN_NLS_APPKEY", "")
ALIYUN_NLS_REGION = os.getenv("ALIYUN_NLS_REGION", "cn-shanghai")
ALIYUN_NLS_GATEWAY = os.getenv(
    "ALIYUN_NLS_GATEWAY",
    "wss://nls-gateway.cn-shanghai.aliyuncs.com/ws/v1",
)
