# Generated by Django 5.1.6 on 2025-06-13 10:57

import tools.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, verbose_name="微信二维码用scene获取的数据"
                    ),
                ),
                ("img", models.TextField(default="", verbose_name="img base64")),
                (
                    "remark",
                    models.CharField(default="", max_length=1024, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "微信二维码表",
            },
        ),
    ]
