# Generated by Django 5.1.6 on 2025-07-29 16:55

import tools.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "key",
                    models.CharField(default="", max_length=32, verbose_name="key"),
                ),
                ("text", models.TextField(default="", verbose_name="协议内容")),
            ],
            options={
                "verbose_name": "用户/隐私协议",
            },
        ),
    ]
