# Generated by Django 5.1.6 on 2025-11-28 14:09

import tools.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_agreement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "key",
                    models.CharField(
                        default="", max_length=32, unique=True, verbose_name="key"
                    ),
                ),
                (
                    "token",
                    models.CharField(default="", max_length=1024, verbose_name="token"),
                ),
                ("expire_time", models.DateTimeField(verbose_name="过期时间")),
            ],
            options={
                "verbose_name": "别的平台token管理",
            },
        ),
    ]
