# Generated by Django 5.1.6 on 2025-02-24 20:00

import tools.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=256, verbose_name="姓名"),
                ),
                ("sex", models.BooleanField(default=0, verbose_name="性别")),
                ("age", models.IntegerField(default=0, verbose_name="年龄")),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="就诊日期"),
                ),
                (
                    "phone",
                    models.CharField(default="", max_length=32, verbose_name="手机号"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        default="", max_length=32, verbose_name="婚姻状况"
                    ),
                ),
                (
                    "job",
                    models.CharField(default="", max_length=256, verbose_name="职业"),
                ),
                (
                    "origin",
                    models.CharField(default="", max_length=256, verbose_name="籍贯"),
                ),
            ],
            options={
                "verbose_name": "患者",
            },
        ),
    ]
