# Generated by Django 5.1.6 on 2025-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="marital_status",
            field=models.CharField(
                choices=[
                    ("未婚", "未婚"),
                    ("已婚", "已婚"),
                    ("离异", "离异"),
                    ("丧偶", "丧偶"),
                ],
                default="",
                max_length=32,
                verbose_name="婚姻状况",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                choices=[("男", "男"), ("女", "女")],
                default="男",
                max_length=32,
                verbose_name="性别",
            ),
        ),
    ]
