# Generated by Django 5.1.6 on 2025-02-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0003_patient_result_answer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="op_answer",
            new_name="op_radio_answer",
        ),
        migrations.AddField(
            model_name="answer",
            name="op_input_answer",
            field=models.JSONField(default={}, verbose_name="填写的答案"),
        ),
    ]
