# Generated by Django 5.1.6 on 2025-02-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_rename_op_answer_answer_op_radio_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="date",
            field=models.DateTimeField(verbose_name="就诊日期"),
        ),
    ]
