# Generated by Django 5.1.6 on 2025-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0005_alter_patient_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="file",
            field=models.CharField(
                default="", max_length=1024, verbose_name="答题详情文件"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="token",
            field=models.CharField(default="", max_length=256),
        ),
    ]
