# Generated by Django 5.1.6 on 2025-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0006_patient_file_patient_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="anxiety_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="yiyu_level",
            field=models.IntegerField(default=0),
        ),
    ]
