# Generated by Django 5.1.6 on 2025-03-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0007_patient_anxiety_level_patient_score_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="patient",
            name="anxiety_level",
            field=models.IntegerField(default=0, verbose_name="焦虑等级"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="score",
            field=models.IntegerField(default=0, verbose_name="总分数"),
        ),
        migrations.AlterField(
            model_name="patient",
            name="yiyu_level",
            field=models.IntegerField(default=0, verbose_name="抑郁等级"),
        ),
        migrations.RemoveField(
            model_name="answer",
            name="q",
        ),
    ]
