# Generated by Django 5.1.6 on 2025-03-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0008_alter_answer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="all_answer",
            field=models.JSONField(default={}, verbose_name="所有答案"),
        ),
        migrations.AddField(
            model_name="answer",
            name="q_id",
            field=models.IntegerField(default=0, verbose_name="对应的level1题目id"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["p", "q_id"], name="pq"),
        ),
    ]
