# Generated by Django 5.1.6 on 2025-03-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0009_answer_all_answer_answer_q_id_answer_pq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="all_answer",
            field=models.JSONField(default=dict, verbose_name="所有答案"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="op_input_answer",
            field=models.JSONField(default=dict, verbose_name="填写的答案"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="op_radio_answer",
            field=models.JSONField(default=dict, verbose_name="选项的答案"),
        ),
    ]
