# Generated by Django 5.1.6 on 2025-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "patient",
            "0010_alter_answer_all_answer_alter_answer_op_input_answer_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="anxiety_level",
            new_name="jl_level",
        ),
        migrations.RenameField(
            model_name="patient",
            old_name="yiyu_level",
            new_name="yu_level",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="score",
        ),
        migrations.AddField(
            model_name="patient",
            name="jl_score",
            field=models.FloatField(default=0.0, verbose_name="焦虑分数"),
        ),
        migrations.AddField(
            model_name="patient",
            name="yu_score",
            field=models.FloatField(default=0.0, verbose_name="抑郁分数"),
        ),
    ]
