# Generated by Django 5.1.6 on 2025-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0011_rename_anxiety_level_patient_jl_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="blood_pressure",
            field=models.CharField(default="", max_length=256, verbose_name="血压"),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_sugar",
            field=models.CharField(default="", max_length=256, verbose_name="血糖"),
        ),
        migrations.AddField(
            model_name="patient",
            name="blood_type",
            field=models.CharField(default="", max_length=256, verbose_name="血型"),
        ),
        migrations.AddField(
            model_name="patient",
            name="height",
            field=models.CharField(default="", max_length=32, verbose_name="身高cm"),
        ),
        migrations.AddField(
            model_name="patient",
            name="weight",
            field=models.CharField(default="", max_length=32, verbose_name="体重kg"),
        ),
    ]
