# Generated by Django 5.1.6 on 2025-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0012_patient_blood_pressure_patient_blood_sugar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="origin",
            field=models.CharField(
                default="", max_length=256, verbose_name="长期居住地"
            ),
        ),
    ]
