# Generated by Django 5.1.6 on 2025-06-10 15:51

import django.db.models.deletion
import tools.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0013_alter_patient_origin"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "openid",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        unique=True,
                        verbose_name="唯一标识",
                    ),
                ),
                (
                    "nick_name",
                    models.CharField(
                        default="", max_length=1024, verbose_name="微信昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(default="", max_length=1024, verbose_name="头像"),
                ),
                ("token", models.CharField(default="", max_length=256)),
            ],
            options={
                "verbose_name": "用户唯一标识",
            },
        ),
        migrations.RemoveField(
            model_name="patient",
            name="token",
        ),
        migrations.AddField(
            model_name="patient",
            name="company",
            field=models.CharField(
                default="", max_length=256, verbose_name="企业/学校"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="department",
            field=models.CharField(
                default="", max_length=256, verbose_name="部门/院系"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="q_type",
            field=models.CharField(
                default="common", max_length=32, verbose_name="问卷类型"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="people",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to="patient.people",
            ),
        ),
    ]
