# Generated by Django 5.1.6 on 2025-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0014_people_remove_patient_token_patient_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="history_show",
            field=models.BooleanField(
                default=False, verbose_name="是否在历史问卷中展示"
            ),
        ),
    ]
