# Generated by Django 5.1.6 on 2025-06-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0015_patient_history_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="doctor_id",
            field=models.IntegerField(default=0, verbose_name="医生id"),
        ),
    ]
