# Generated by Django 5.1.6 on 2025-07-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0016_patient_doctor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="phone",
            field=models.CharField(default="", max_length=32, verbose_name="手机号"),
        ),
    ]
