# Generated by Django 5.1.6 on 2025-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0017_people_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="people",
            name="openid",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="唯一标识",
            ),
        ),
    ]
