# Generated by Django 5.1.6 on 2025-11-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0018_alter_people_openid"),
    ]

    operations = [
        migrations.AddField(
            model_name="people",
            name="password",
            field=models.CharField(default="", max_length=1024, verbose_name="密码"),
        ),
    ]
