# Generated by Django 5.1.6 on 2026-03-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0019_people_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="allergy",
            field=models.CharField(
                default="", max_length=256, verbose_name="药物过敏史"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="birthday",
            field=models.CharField(default="", max_length=256, verbose_name="出生日期"),
        ),
        migrations.AddField(
            model_name="patient",
            name="nation",
            field=models.CharField(default="", max_length=256, verbose_name="民族"),
        ),
    ]
