# Generated by Django 5.1.6 on 2026-03-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0020_patient_allergy_patient_birthday_patient_nation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="birthday",
            field=models.CharField(default="", max_length=256, verbose_name="出生年月"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["phone", "name"], name="pn"),
        ),
    ]
