# Generated by Django 5.1.6 on 2025-04-27 15:36

import django.db.models.deletion
import tools.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patient", "0012_patient_blood_pressure_patient_blood_sugar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "mark",
                    models.CharField(
                        default="", max_length=256, verbose_name="每个请求一个标记"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(default="", max_length=256, verbose_name="模型"),
                ),
                ("runtime", models.FloatField(default=0.0, verbose_name="运行时间(s)")),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, verbose_name="问的token数量"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, verbose_name="回答token数量"),
                ),
                (
                    "messages",
                    models.TextField(default="", verbose_name="问大模型的参数"),
                ),
                ("output", models.TextField(default="", verbose_name="大模型的输出")),
                ("err", models.BooleanField(default=False, verbose_name="是否报错")),
                ("err_msg", models.TextField(default="", verbose_name="报错信息")),
                ("uid", models.IntegerField(default=0, verbose_name="请求的用户")),
            ],
            options={
                "verbose_name": "大模型问答记录",
            },
        ),
        migrations.CreateModel(
            name="Revise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    tools.base_model.MyDateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_time",
                    tools.base_model.MyDateTimeField(
                        auto_now=True, verbose_name="更新时间"
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                ("user", models.TextField(default="", verbose_name="用户部分的输入")),
                ("doctor", models.TextField(default="", verbose_name="医生部分的输入")),
                (
                    "revise_output",
                    models.TextField(default="", verbose_name="人工修正的输出"),
                ),
                ("star", models.IntegerField(default=-1, verbose_name="星级")),
                (
                    "p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revise",
                        to="patient.patient",
                    ),
                ),
                (
                    "r",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revise",
                        to="llm.record",
                    ),
                ),
            ],
            options={
                "verbose_name": "针对患者的模型输出进行追加修改",
            },
        ),
    ]
