# Generated by Django 5.1.6 on 2025-04-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="reasoning",
            field=models.TextField(default="", verbose_name="大模型的思考"),
        ),
    ]
