# Generated by Django 5.1.6 on 2025-04-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_record_reasoning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="mark",
            field=models.CharField(
                default="", max_length=256, unique=True, verbose_name="每个请求一个标记"
            ),
        ),
    ]
