# Generated by Django 5.1.6 on 2025-05-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_alter_record_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="uid",
        ),
        migrations.AddField(
            model_name="revise",
            name="question",
            field=models.TextField(default="", verbose_name="用户问卷调查"),
        ),
        migrations.AddField(
            model_name="revise",
            name="uid",
            field=models.IntegerField(default=0, verbose_name="请求的用户"),
        ),
        migrations.AlterField(
            model_name="revise",
            name="r",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revise",
                to="llm.record",
            ),
        ),
        migrations.AlterField(
            model_name="revise",
            name="user",
            field=models.TextField(default="", verbose_name="用户基本信息"),
        ),
    ]
