# Generated by Django 5.1.6 on 2025-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0004_remove_record_uid_revise_question_revise_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revise",
            name="prescription",
            field=models.TextField(default="", verbose_name="推荐的处方"),
        ),
    ]
