# Generated by Django 5.1.6 on 2025-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0005_revise_prescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="mark",
            field=models.CharField(
                default="", max_length=255, unique=True, verbose_name="每个请求一个标记"
            ),
        ),
    ]
