# Generated by Django 5.1.6 on 2025-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0006_alter_record_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="revise",
            name="dialogue",
            field=models.TextField(default="", verbose_name="医患对话"),
        ),
    ]
