# Generated by Django 5.1.6 on 2026-03-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0007_revise_dialogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="revise",
            name="case",
            field=models.TextField(default="", verbose_name="病历输出"),
        ),
        migrations.AddField(
            model_name="revise",
            name="revise_case",
            field=models.TextField(default="", verbose_name="人工修正的病历输出"),
        ),
    ]
